[tool.ruff]
line-length = 88
fix = true

[tool.ruff.lint]
unfixable = [
    "E711", # prevents == to be replaced with is (sqlalchemy)
    "F401", # prevents imports in __init__.py to be deleted
]
ignore = [
    # Whitespace before ':' (black compatibility)
    "E203",
    # Line too long (black doesn't handle long strings)
    "E501",
    # from ... import *
    "F403",
    # Comparison to `None` should be `cond is None` (sqlalchemy)
    "E711"

]
select = [
    "E", # pycodestyle errors
    "F", # pyflakes
    "I", # isort
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ["app"]
